# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Andrew Zhang
title: Senior AI Algorithm Engineer
email: kazenokizi@gmail.com
website: www.github.com/kazenokizi

# Social links
twitter_username: kazenokizi
github_username:  kazenokizi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/avataaars.png
about_content: | # this will include new lines to allow paragraphs
  I love to design, implement and optimise interesting algorithms for various scenarios including mobile devices, self-driving cars and smart factory. 

  I am most skilled in: <mark>Unsupervised machine learning</mark> and <mark>cooking</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Scuba-diving
   - Jogging
   - Reading

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
